# Generated by Django 3.1.5 on 2021-01-07 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_num', models.IntegerField()),
                ('acct_type', models.CharField(choices=[('S', 'Savings'), ('C', 'Checking')], max_length=1)),
                ('hold_pattern', models.CharField(choices=[('S', 'Single'), ('J', 'Joint')], max_length=1)),
                ('currency', models.CharField(max_length=10)),
                ('balance', models.FloatField()),
                ('min_balance', models.FloatField()),
                ('mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn_date', models.DateField()),
                ('trn_narration', models.CharField(max_length=100)),
                ('trn_ref_no', models.CharField(max_length=20, null=True)),
                ('trn_amount', models.FloatField()),
                ('trn_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_banking_system.account')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
