# Generated by Django 3.1.5 on 2021-01-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acct_type',
            field=models.CharField(choices=[('S', 'Savings'), ('C', 'Current')], max_length=1),
        ),
    ]
